SELECT
	DISTINCT MEMBER_NAME AS MEMBER,
	MEMBER_RENTAL_DATE AS DATE
FROM
	MEMBERS
INNER JOIN MEMBERS_MOVIE_RENTAL ON
	MEMBERS.MEMBER_ID = MEMBERS_MOVIE_RENTAL.MEMBER_ID
WHERE 
	MEMBER_RENTAL_DATE BETWEEN '2010-01-01' AND '2015-12-31';