SELECT
	COUNT(DISTINCT MA.ACTOR_ID) AS ACTORS,
	COUNT(DISTINCT D.DIRECTOR_ID) AS DIRECTORS
FROM
	MOVIES_ACTORS MA
JOIN MOVIES M ON
	MA.MOVIE_ID = M.MOVIE_ID
JOIN DIRECTORS D ON
	M.DIRECTOR_ID = D.DIRECTOR_ID
JOIN STUDIOS S ON
	M.STUDIO_ID = S.STUDIO_ID
WHERE
	S.STUDIO_ACTIVE = 0;