SELECT
    DIRECTOR_NAME,
    AGE
FROM
    (
    SELECT
        DIRECTOR_NAME,
        DATEDIFF(YEAR, DIRECTOR_BIRTH_DATE, TODAY()) AS "AGE",
        DIRECTOR_DEAD_DATE
    FROM
        DIRECTORS)
WHERE
    AGE <= 50
    AND DIRECTOR_DEAD_DATE IS NULL;