SELECT
	D.DIRECTOR_NAME AS DIRECTOR,
	COUNT (*) AS RENTALS
FROM
	DIRECTORS D
JOIN MOVIES M ON
	D.DIRECTOR_ID = M.DIRECTOR_ID
JOIN MEMBERS_MOVIE_RENTAL MR ON
	M.MOVIE_ID = MR.MOVIE_ID
GROUP BY
	D.DIRECTOR_NAME
ORDER BY
	RENTALS DESC
LIMIT 1;