SELECT
	M.MOVIE_NAME AS MOVIE,
	D.DIRECTOR_NAME AS DIRECTOR,
	D.DIRECTOR_DEAD_DATE,
	D.DIRECTOR_BIRTH_DATE,
	M.MOVIE_LAUNCH_DATE
FROM
	MOVIES M
JOIN DIRECTORS D ON
	M.DIRECTOR_ID = D.DIRECTOR_ID
WHERE
	D.DIRECTOR_DEAD_DATE < M.MOVIE_LAUNCH_DATE
	OR D.DIRECTOR_BIRTH_DATE > M.MOVIE_LAUNCH_DATE;