SELECT
	A.ACTOR_NAME AS ACTOR,
	COUNT(*) AS NOMINATIONS
FROM
	ACTORS A
JOIN MOVIES_ACTORS MA ON
	A.ACTOR_ID = MA.ACTOR_ID
JOIN MOVIES M ON
	MA.MOVIE_ID = M.MOVIE_ID
JOIN AWARDS AW ON
	M.MOVIE_ID = AW.MOVIE_ID
WHERE
	AW.AWARD_NOMINATION > 0
	AND AW.AWARD_WIN = 0
GROUP BY
	A.ACTOR_NAME;