SELECT
	DISTINCT ME.MEMBER_NAME,
	ME.MEMBER_TOWN,
	ME.MEMBER_PHONE
FROM
	MEMBERS ME
JOIN MEMBERS_MOVIE_RENTAL MR ON
	ME.MEMBER_ID = MR.MEMBER_ID
JOIN MOVIES M ON
	MR.MOVIE_ID = M.MOVIE_ID
JOIN AWARDS A ON
	M.MOVIE_ID = A.MOVIE_ID
WHERE
	A.AWARD_NOMINATION > 150
	AND A.AWARD_WIN <50;