SELECT
	D.DIRECTOR_NAME, COUNT(*) AS TOTAL
FROM
	DIRECTORS D
JOIN MOVIES M ON
	D.DIRECTOR_ID = M.DIRECTOR_ID
WHERE
	YEAR (M.MOVIE_LAUNCH_DATE) BETWEEN 1960 AND 1989
	AND UPPER(M.MOVIE_NAME) LIKE '%THE%'
GROUP BY
	D.DIRECTOR_ID, D.DIRECTOR_NAME;