SELECT
    COUNT(*) N_PELICULAS,DIRECTOR_NAME
FROM
    (
    SELECT
        m.MOVIE_NAME ,
        m.MOVIE_LAUNCH_DATE ,
        d.DIRECTOR_BIRTH_DATE,
        DATEDIFF(YEAR, d.DIRECTOR_BIRTH_DATE, m.MOVIE_LAUNCH_DATE ) YEARS,
        d.DIRECTOR_ID,
        d.DIRECTOR_NAME 
    FROM
        MOVIES m
    JOIN DIRECTORS d ON
        d.DIRECTOR_ID = m.DIRECTOR_ID
    WHERE
        DATEDIFF(YEAR, d.DIRECTOR_BIRTH_DATE, m.MOVIE_LAUNCH_DATE ) < 41
) EDAD_PELICULAS
GROUP BY DIRECTOR_ID, DIRECTOR_NAME