SELECT
    MOVIE_NAME AS FIRST_RENTED_MOVIE
FROM
    MEMBERS_MOVIE_RENTAL ma
JOIN
    MOVIES m ON ma.MOVIE_ID = m.MOVIE_ID
JOIN
    MEMBERS mb ON ma.MEMBER_ID = mb.MEMBER_ID
JOIN
    NATIONALITIES n ON RIGHT(mb.MEMBER_PHONE, 1) = n.NATIONALITY_ID
ORDER BY
    ma.MEMBER_RENTAL_DATE
LIMIT 1;

