SELECT M.MOVIE_NAME AS MOVIE, MIN (M.MOVIE_DURATION) AS DURATION
FROM MOVIES M 
JOIN MEMBERS_MOVIE_RENTAL MR ON MR.MOVIE_ID = M.MOVIE_ID
WHERE MR.MEMBER_RENTAL_DATE BETWEEN '2017-01-25' AND '2019-01-25'
GROUP BY M.MOVIE_NAME;