SELECT
	M.MOVIE_NAME AS NAME,
	N.NATIONALITY_NAME,
	D.DIRECTOR_NAME AS DIRECTOR
FROM
	MOVIES M
JOIN DIRECTORS D ON
	M.DIRECTOR_ID = D.DIRECTOR_ID
JOIN NATIONALITIES N ON
	M.NATIONALITY_ID = N.NATIONALITY_ID