SELECT
	S.STUDIO_NAME AS STUDIO,
	COUNT(AW.AWARD_WIN) AS TOTAL_AWARDS
FROM
	STUDIOS S
JOIN MOVIES M ON
	S.STUDIO_ID = M.STUDIO_ID
JOIN AWARDS AW ON
	M.MOVIE_ID = AW.MOVIE_ID
GROUP BY
	S.STUDIO_NAME;