SELECT 
	MOVIE_NAME AS MOVIE,
	DIRECTOR_NAME AS DIRECTOR
FROM
	MOVIES
INNER JOIN DIRECTORS ON
	MOVIES.DIRECTOR_ID = DIRECTORS.DIRECTOR_ID
WHERE 
	YEAR (DIRECTOR_BIRTH_DATE) >= 1980
	AND DIRECTOR_DEAD_DATE IS NULL;