SELECT
	STUDIO_NAME,
	MAX(GENRE_NAME) AS FAVORITE_GENRE
FROM
	(
	SELECT
		STUDIO_NAME,
		GENRE_NAME,
		COUNT(*) AS GENRE_COUNT
	FROM
		STUDIOS s
	JOIN 
        MOVIES m ON
		s.STUDIO_ID = m.STUDIO_ID
	JOIN 
        GENRES g ON
		m.GENRE_ID = g.GENRE_ID
	GROUP BY
		STUDIO_NAME,
		GENRE_NAME
	ORDER BY
		STUDIO_NAME,
		GENRE_COUNT DESC
) AS GENRE_COUNTS
GROUP BY
	STUDIO_NAME;